create or replace PROCEDURE               RECORD_ALARM_QUANTITY_ABNORMAL_ABNORMALCASE_PROCEDURE
(
    GASDAY_INPUT IN DATE
) AS
    CURSOR RAW_DATA IS
        SELECT * FROM MASTER_METER.RECORD_DAILY_GET_QUANTITY_RAW_DATA WHERE TRUNC(GASDAY) = TRUNC(GASDAY_INPUT);
    TYPE DATA_RAW IS TABLE OF RAW_DATA%ROWTYPE;
    DATA DATA_RAW;
    DESCRIPTION VARCHAR(500 BYTE);
BEGIN
    OPEN RAW_DATA;
    LOOP FETCH RAW_DATA BULK COLLECT INTO DATA; EXIT WHEN DATA.COUNT = 0; 
        FOR i IN 1..DATA.COUNT LOOP
            IF DATA(i).MONTHLY_BILLING_ENERGY < 0 AND DATA(i).MONTHLY_BILLING_ENERGY <> -2 AND DATA(i).MONTHLY_BILLING_VOLUME < 0 AND DATA(i).MONTHLY_BILLING_VOLUME <> -2 THEN
                DESCRIPTION := 'MONTHLY BILLING ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,1,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).DAILY_BILLING_ENERGY < 0 AND DATA(i).DAILY_BILLING_ENERGY <> -2 AND DATA(i).DAILY_BILLING_VOLUME < 0 AND DATA(i).DAILY_BILLING_VOLUME <> -2 THEN
                DESCRIPTION := 'DAILY BILLING ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,2,2,DESCRIPTION,12);
            END IF;

-------------------------------------------------------------------GMDR SCADA-----------------------------------------------------------------------------------------------------------------------            
            IF DATA(i).GMDR_SCADA_MAIN_1_SATSTDVOL < 0 AND DATA(i).GMDR_SCADA_MAIN_1_SATSTDVOL <> -2 AND DATA(i).GMDR_SCADA_MAIN_1_STDVOL < 0 AND DATA(i).GMDR_SCADA_MAIN_1_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR SCADA MAIN 1 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,3,1,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_SCADA_MAIN_2_SATSTDVOL < 0 AND DATA(i).GMDR_SCADA_MAIN_2_SATSTDVOL <> -2 AND DATA(i).GMDR_SCADA_MAIN_2_STDVOL < 0 AND DATA(i).GMDR_SCADA_MAIN_2_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR SCADA MAIN 2 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,3,2,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_SCADA_MAIN_3_SATSTDVOL < 0 AND DATA(i).GMDR_SCADA_MAIN_3_SATSTDVOL <> -2 AND DATA(i).GMDR_SCADA_MAIN_3_STDVOL < 0 AND DATA(i).GMDR_SCADA_MAIN_3_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR SCADA MAIN 3 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,3,3,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_SCADA_MAIN_4_SATSTDVOL < 0 AND DATA(i).GMDR_SCADA_MAIN_4_SATSTDVOL <> -2 AND DATA(i).GMDR_SCADA_MAIN_4_STDVOL < 0 AND DATA(i).GMDR_SCADA_MAIN_4_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR SCADA MAIN 4 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,3,4,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_SCADA_MAIN_5_SATSTDVOL < 0 AND DATA(i).GMDR_SCADA_MAIN_5_SATSTDVOL <> -2 AND DATA(i).GMDR_SCADA_MAIN_5_STDVOL < 0 AND DATA(i).GMDR_SCADA_MAIN_5_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR SCADA MAIN 5 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,3,5,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_SCADA_MAIN_6_SATSTDVOL < 0 AND DATA(i).GMDR_SCADA_MAIN_6_SATSTDVOL <> -2 AND DATA(i).GMDR_SCADA_MAIN_6_STDVOL < 0 AND DATA(i).GMDR_SCADA_MAIN_6_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR SCADA MAIN 6 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,3,6,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_SCADA_BACK_1_SATSTDVOL < 0 AND DATA(i).GMDR_SCADA_BACK_1_SATSTDVOL <> -2 AND DATA(i).GMDR_SCADA_BACK_1_STDVOL < 0 AND DATA(i).GMDR_SCADA_BACK_1_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR SCADA BACK 1 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,3,7,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_SCADA_BACK_2_SATSTDVOL < 0 AND DATA(i).GMDR_SCADA_BACK_2_SATSTDVOL <> -2 AND DATA(i).GMDR_SCADA_BACK_2_STDVOL < 0 AND DATA(i).GMDR_SCADA_BACK_2_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR SCADA BACK 2 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,3,8,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_SCADA_BACK_3_SATSTDVOL < 0 AND DATA(i).GMDR_SCADA_BACK_3_SATSTDVOL <> -2 AND DATA(i).GMDR_SCADA_BACK_3_STDVOL < 0 AND DATA(i).GMDR_SCADA_BACK_3_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR SCADA BACK 3 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,3,9,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_SCADA_BACK_4_SATSTDVOL < 0 AND DATA(i).GMDR_SCADA_BACK_4_SATSTDVOL <> -2 AND DATA(i).GMDR_SCADA_BACK_4_STDVOL < 0 AND DATA(i).GMDR_SCADA_BACK_4_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR SCADA BACK 4 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,3,10,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_SCADA_BACK_5_SATSTDVOL < 0 AND DATA(i).GMDR_SCADA_BACK_5_SATSTDVOL <> -2 AND DATA(i).GMDR_SCADA_BACK_5_STDVOL < 0 AND DATA(i).GMDR_SCADA_BACK_5_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR SCADA BACK 5 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,3,11,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_SCADA_BACK_6_SATSTDVOL < 0 AND DATA(i).GMDR_SCADA_BACK_6_SATSTDVOL <> -2 AND DATA(i).GMDR_SCADA_BACK_6_STDVOL < 0 AND DATA(i).GMDR_SCADA_BACK_6_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR SCADA BACK 6 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,3,12,2,DESCRIPTION,12);
            END IF;

----------------------------------------------------------GMDR CLIENT-------------------------------------------------------------------------------------------------------------------------------------
            IF DATA(i).GMDR_CLIENT_MAIN_1_SATSTDVOL < 0 AND DATA(i).GMDR_CLIENT_MAIN_1_SATSTDVOL <> -2 AND DATA(i).GMDR_CLIENT_MAIN_1_STDVOL < 0 AND DATA(i).GMDR_CLIENT_MAIN_1_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR CLIENT MAIN 1 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,4,1,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_CLIENT_MAIN_2_SATSTDVOL < 0 AND DATA(i).GMDR_CLIENT_MAIN_2_SATSTDVOL <> -2 AND  DATA(i).GMDR_CLIENT_MAIN_2_STDVOL < 0 AND DATA(i).GMDR_CLIENT_MAIN_2_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR CLIENT MAIN 2 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,4,2,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_CLIENT_MAIN_3_SATSTDVOL < 0 AND DATA(i).GMDR_CLIENT_MAIN_3_SATSTDVOL <> -2 AND DATA(i).GMDR_CLIENT_MAIN_3_STDVOL < 0 AND DATA(i).GMDR_CLIENT_MAIN_3_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR CLIENT MAIN 3 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,4,3,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_CLIENT_MAIN_4_SATSTDVOL < 0 AND DATA(i).GMDR_CLIENT_MAIN_4_SATSTDVOL <> -2 AND DATA(i).GMDR_CLIENT_MAIN_4_STDVOL < 0 AND DATA(i).GMDR_CLIENT_MAIN_4_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR CLIENT MAIN 4 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,4,4,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_CLIENT_MAIN_5_SATSTDVOL < 0 AND DATA(i).GMDR_CLIENT_MAIN_5_SATSTDVOL <> -2 AND DATA(i).GMDR_CLIENT_MAIN_5_STDVOL < 0 AND DATA(i).GMDR_CLIENT_MAIN_5_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR CLIENT_ AIN 5 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,4,5,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_CLIENT_MAIN_6_SATSTDVOL < 0 AND DATA(i).GMDR_CLIENT_MAIN_6_SATSTDVOL <> -2 AND DATA(i).GMDR_CLIENT_MAIN_6_STDVOL < 0 AND DATA(i).GMDR_CLIENT_MAIN_6_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR CLIENT MAIN 6 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,4,6,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_CLIENT_BACK_1_SATSTDVOL < 0 AND DATA(i).GMDR_CLIENT_BACK_1_SATSTDVOL <> -2 AND DATA(i).GMDR_CLIENT_BACK_1_STDVOL < 0 AND DATA(i).GMDR_CLIENT_BACK_1_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR CLIENT BACK 1 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,4,7,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_CLIENT_BACK_2_SATSTDVOL < 0 AND DATA(i).GMDR_CLIENT_BACK_2_SATSTDVOL <> -2 AND DATA(i).GMDR_CLIENT_BACK_2_STDVOL < 0 AND DATA(i).GMDR_CLIENT_BACK_2_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR CLIENT BACK 2 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,4,8,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_CLIENT_BACK_3_SATSTDVOL < 0 AND DATA(i).GMDR_CLIENT_BACK_3_SATSTDVOL <> -2 AND DATA(i).GMDR_CLIENT_BACK_3_STDVOL < 0 AND DATA(i).GMDR_CLIENT_BACK_3_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR CLIENT BACK 3 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,4,9,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_CLIENT_BACK_4_SATSTDVOL < 0 AND DATA(i).GMDR_CLIENT_BACK_4_SATSTDVOL <> -2 AND DATA(i).GMDR_CLIENT_BACK_4_STDVOL < 0 AND DATA(i).GMDR_CLIENT_BACK_4_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR CLIENT BACK 4 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,4,10,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_CLIENT_BACK_5_SATSTDVOL < 0 AND DATA(i).GMDR_CLIENT_BACK_5_SATSTDVOL <> -2 AND DATA(i).GMDR_CLIENT_BACK_5_STDVOL < 0 AND DATA(i).GMDR_CLIENT_BACK_5_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR CLIENT BACK 5 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,4,11,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).GMDR_CLIENT_BACK_6_SATSTDVOL < 0 AND DATA(i).GMDR_CLIENT_BACK_6_SATSTDVOL <> -2 AND DATA(i).GMDR_CLIENT_BACK_6_STDVOL < 0 AND DATA(i).GMDR_CLIENT_BACK_6_STDVOL <> -2 THEN
                DESCRIPTION := 'GMDR CLIENT BACK 6 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,4,12,2,DESCRIPTION,12);
            END IF;

-------------------------------------------------------ARCHIVE SCADA------------------------------------------------------------------------------------------------------
            IF DATA(i).ARCHIVE_SCADA_VOLUME_TAG_1 < 0 AND DATA(i).ARCHIVE_SCADA_VOLUME_TAG_1 <> -2 THEN
                DESCRIPTION := 'ARCHIVE SCADA VOLUME TAG 1 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,5,1,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).ARCHIVE_SCADA_VOLUME_TAG_2 < 0 AND DATA(i).ARCHIVE_SCADA_VOLUME_TAG_2 <> -2 THEN
                DESCRIPTION := 'ARCHIVE SCADA VOLUME TAG 2 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,5,2,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).ARCHIVE_SCADA_VOLUME_TAG_3 < 0 AND DATA(i).ARCHIVE_SCADA_VOLUME_TAG_3 <> -2 THEN
                DESCRIPTION := 'ARCHIVE SCADA VOLUME TAG 3 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,5,3,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).ARCHIVE_SCADA_VOLUME_TAG_4 < 0 AND DATA(i).ARCHIVE_SCADA_VOLUME_TAG_4 <> -2 THEN
                DESCRIPTION := 'ARCHIVE SCADA VOLUME TAG 4 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,5,4,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).ARCHIVE_SCADA_VOLUME_TAG_5 < 0 AND DATA(i).ARCHIVE_SCADA_VOLUME_TAG_5 <> -2 THEN
                DESCRIPTION := 'ARCHIVE SCADA VOLUME TAG 5 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,5,5,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).ARCHIVE_SCADA_VOLUME_TAG_6 < 0 AND DATA(i).ARCHIVE_SCADA_VOLUME_TAG_6 <> -2 THEN
                DESCRIPTION := 'ARCHIVE SCADA VOLUME TAG 6 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,5,6,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).ARCHIVE_SCADA_ENERGY_TAG_1 < 0 AND DATA(i).ARCHIVE_SCADA_ENERGY_TAG_1 <> -2 THEN
                DESCRIPTION := 'ARCHIVE SCADA ENERGY TAG 1 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,5,1,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).ARCHIVE_SCADA_ENERGY_TAG_2 < 0 AND DATA(i).ARCHIVE_SCADA_ENERGY_TAG_2 <> -2 THEN
                DESCRIPTION := 'ARCHIVE SCADA ENERGY TAG 2 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,5,2,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).ARCHIVE_SCADA_ENERGY_TAG_3 < 0 AND DATA(i).ARCHIVE_SCADA_ENERGY_TAG_3 <> -2 THEN
                DESCRIPTION := 'ARCHIVE SCADA ENERGY TAG 3 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,5,3,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).ARCHIVE_SCADA_ENERGY_TAG_4 < 0 AND DATA(i).ARCHIVE_SCADA_ENERGY_TAG_4 <> -2 THEN
                DESCRIPTION := 'ARCHIVE SCADA ENERGY TAG 4 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,5,4,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).ARCHIVE_SCADA_ENERGY_TAG_5 < 0 AND DATA(i).ARCHIVE_SCADA_ENERGY_TAG_5 <> -2 THEN
                DESCRIPTION := 'ARCHIVE SCADA ENERGY TAG 5 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,5,5,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).ARCHIVE_SCADA_ENERGY_TAG_6 < 0 AND DATA(i).ARCHIVE_SCADA_ENERGY_TAG_6 <> -2 THEN
                DESCRIPTION := 'ARCHIVE SCADA ENERGY TAG 6 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,5,6,2,DESCRIPTION,12);
            END IF;

------------------------------------------------------REALTIME SCADA--------------------------------------------------------------------------------------------------------
            IF DATA(i).REALTIME_SCADA_VOLUME_TAG_1 < 0 AND DATA(i).REALTIME_SCADA_VOLUME_TAG_1 <> -2 THEN
                DESCRIPTION := 'REALTIME SCADA VOLUME TAG 1 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,6,1,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).REALTIME_SCADA_VOLUME_TAG_2 < 0 AND DATA(i).REALTIME_SCADA_VOLUME_TAG_2 <> -2 THEN
                DESCRIPTION := 'REALTIME SCADA VOLUME TAG 2 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,6,2,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).REALTIME_SCADA_VOLUME_TAG_3 < 0 AND DATA(i).REALTIME_SCADA_VOLUME_TAG_3 <> -2 THEN
                DESCRIPTION := 'REALTIME SCADA VOLUME TAG 3 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,6,3,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).REALTIME_SCADA_VOLUME_TAG_4 < 0 AND DATA(i).REALTIME_SCADA_VOLUME_TAG_4 <> -2 THEN
                DESCRIPTION := 'REALTIME SCADA VOLUME TAG 4 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,6,4,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).REALTIME_SCADA_VOLUME_TAG_5 < 0 AND DATA(i).REALTIME_SCADA_VOLUME_TAG_5 <> -2 THEN
                DESCRIPTION := 'REALTIME SCADA VOLUME TAG 5 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,6,5,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).REALTIME_SCADA_VOLUME_TAG_6 < 0 AND DATA(i).REALTIME_SCADA_VOLUME_TAG_6 <> -2 THEN
                DESCRIPTION := 'REALTIME SCADA VOLUME TAG 6 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,6,6,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).REALTIME_SCADA_ENERGY_TAG_1 < 0 AND DATA(i).REALTIME_SCADA_ENERGY_TAG_1 <> -2 THEN
                DESCRIPTION := 'REALTIME SCADA ENERGY TAG 1 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,6,7,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).REALTIME_SCADA_ENERGY_TAG_2 < 0 AND DATA(i).REALTIME_SCADA_ENERGY_TAG_2 <> -2 THEN
                DESCRIPTION := 'REALTIME SCADA ENERGY TAG 2 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,6,8,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).REALTIME_SCADA_ENERGY_TAG_3 < 0 AND DATA(i).REALTIME_SCADA_ENERGY_TAG_3 <> -2 THEN
                DESCRIPTION := 'REALTIME SCADA ENERGY TAG 3 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,6,9,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).REALTIME_SCADA_ENERGY_TAG_4 < 0 AND DATA(i).REALTIME_SCADA_ENERGY_TAG_4 <> -2 THEN
                DESCRIPTION := 'REALTIME SCADA ENERGY TAG 4 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,6,10,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).REALTIME_SCADA_ENERGY_TAG_5 < 0 AND DATA(i).REALTIME_SCADA_ENERGY_TAG_5 <> -2 THEN
                DESCRIPTION := 'REALTIME SCADA ENERGY TAG 5 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,6,11,2,DESCRIPTION,12);
            END IF;
            IF DATA(i).REALTIME_SCADA_ENERGY_TAG_6 < 0 AND DATA(i).REALTIME_SCADA_ENERGY_TAG_6 <> -2 THEN
                DESCRIPTION := 'REALTIME SCADA ENERGY TAG 6 ค่าผิดปกติ';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION,ABNORMAL_CASE)VALUES(DATA(i).GASDAY,DATA(i).METER_ID,6,12,2,DESCRIPTION,12);
            END IF;
        END LOOP;
    END LOOP;
    CLOSE RAW_DATA;
END RECORD_ALARM_QUANTITY_ABNORMAL_ABNORMALCASE_PROCEDURE;