create or replace PROCEDURE              RECORD_ALARM_QUALITY_OGC_PROCEDURE AS 
    DESCRIPTION VARCHAR2(500 BYTE);
    CURSOR DATA_SUMMARY_REALTIME IS 
        SELECT DATETIME, GHVSAT, QUALITY_POINT_ID 
        FROM MASTER_METER.VW_SUMMARY_REALTIME_QUALITY 
        WHERE GHVSAT IS NOT NULL;

    TYPE OBJ_DATA IS TABLE OF DATA_SUMMARY_REALTIME%ROWTYPE;
    DATA OBJ_DATA;
BEGIN
    OPEN DATA_SUMMARY_REALTIME;
    FETCH DATA_SUMMARY_REALTIME BULK COLLECT INTO DATA;
    CLOSE DATA_SUMMARY_REALTIME;

    FOR I IN 1 .. DATA.COUNT LOOP
        CASE 
            WHEN DATA(I).GHVSAT > 1400 THEN 
                DESCRIPTION := 'ค่า OGC มีค่าเกิน 1400';
                --DBMS_OUTPUT.PUT_LINE('Alarm: ' || DESCRIPTION);
                INSERT INTO MASTER_METER.ALARM_DATA_LOG
                    (GASDAY, SOURCE, RUN, ERROR_TYPE, DESCRIPTION, ABNORMAL_CASE) 
                VALUES
                    (TRUNC(DATA(I).DATETIME), 7, DATA(I).QUALITY_POINT_ID, 2, DESCRIPTION, 14);

            WHEN DATA(I).GHVSAT = -2 THEN 
                DESCRIPTION := 'ค่า OGC ไม่เข้า';
                --DBMS_OUTPUT.PUT_LINE('Alarm: ' || DESCRIPTION);
                INSERT INTO MASTER_METER.ALARM_DATA_LOG
                    (GASDAY, SOURCE, RUN, ERROR_TYPE, DESCRIPTION, ABNORMAL_CASE) 
                VALUES
                    (TRUNC(DATA(I).DATETIME), 7, DATA(I).QUALITY_POINT_ID, 1, DESCRIPTION, 14);

            WHEN DATA(I).GHVSAT = -1 THEN 
                DESCRIPTION := 'ค่า OGC มีปัญหาหน้างาน';
                --DBMS_OUTPUT.PUT_LINE('Alarm: ' || DESCRIPTION || TRUNC(DATA(I).DATETIME));
                INSERT INTO MASTER_METER.ALARM_DATA_LOG
                    (GASDAY, SOURCE, RUN, ERROR_TYPE, DESCRIPTION, ABNORMAL_CASE) 
                VALUES
                    (TRUNC(DATA(I).DATETIME), 7, DATA(I).QUALITY_POINT_ID, 2, DESCRIPTION, 14);

            WHEN DATA(I).GHVSAT = 0 THEN 
                DESCRIPTION := 'OGC มีค่าเป็น 0';
                --DBMS_OUTPUT.PUT_LINE('Alarm: ' || DESCRIPTION);
                INSERT INTO MASTER_METER.ALARM_DATA_LOG
                    (GASDAY, SOURCE, RUN, ERROR_TYPE, DESCRIPTION, ABNORMAL_CASE) 
                VALUES
                    (TRUNC(DATA(I).DATETIME), 7, DATA(I).QUALITY_POINT_ID, 2, DESCRIPTION, 14);

            ELSE 
                NULL;
        END CASE;
    END LOOP;
END RECORD_ALARM_QUALITY_OGC_PROCEDURE;