create or replace PROCEDURE                                                                                                                                                             RECORD_ALARM_QUANTITY_ABNORMAL_DEVIATE_PROCEDURE 
(
  D IN DATE 
) AS 
    VL_DEL_EN                       FLOAT := 0;
    HV                              FLOAT := 0;
    DESCRIPTION                     VARCHAR(500 BYTE);
    CURSOR VW_SUMMARY_DAILY_GET_DATA IS
    SELECT * FROM MASTER_METER.VW_SUMMARY_DAILY_GET_DATA WHERE TRUNC(MASTER_METER.VW_SUMMARY_DAILY_GET_DATA.GASDAY) = TRUNC(D);
    TYPE SUMMARY_DAILY_GET_DATA IS TABLE OF VW_SUMMARY_DAILY_GET_DATA%ROWTYPE;
    DATA3 SUMMARY_DAILY_GET_DATA;
BEGIN
      OPEN VW_SUMMARY_DAILY_GET_DATA;
        LOOP
            FETCH VW_SUMMARY_DAILY_GET_DATA BULK COLLECT INTO DATA3 LIMIT 5000;
            EXIT WHEN DATA3.COUNT = 0;
            FOR COLHV IN 1..DATA3.COUNT LOOP
                HV := 0;
                VL_DEL_EN := 0;
                IF( DATA3(COLHV).OGC_GSAT != -2 AND DATA3(COLHV).OGC_GSAT IS NOT NULL) THEN
                    HV := DATA3(COLHV).OGC_GSAT;
                ELSIF(DATA3(COLHV).ARCHIVE_SCADA_GHVSAT != -2 AND DATA3(COLHV).ARCHIVE_SCADA_GHVSAT IS NOT NULL) THEN
                    HV := DATA3(COLHV).ARCHIVE_SCADA_GHVSAT;
                ELSIF(DATA3(COLHV).REALTIME_SCADA_GHVSAT != -2 AND DATA3(COLHV).REALTIME_SCADA_GHVSAT IS NOT NULL) THEN
                    HV := DATA3(COLHV).REALTIME_SCADA_GHVSAT;
                END IF;
                
                
                IF(DATA3(COLHV).GMDR_SCADA_VOLUME != -2 AND DATA3(COLHV).GMDR_SCADA_VOLUME IS NOT NULL
                   AND DATA3(COLHV).GMDR_SCADA_ENERGY != -2 AND DATA3(COLHV).GMDR_SCADA_ENERGY IS NOT NULL) THEN
                    VL_DEL_EN := DATA3(COLHV).GMDR_SCADA_VOLUME * HV;
                    IF(VL_DEL_EN != 0)THEN
                        IF(ABS(DATA3(COLHV).GMDR_SCADA_ENERGY - VL_DEL_EN / VL_DEL_EN * 100) > 5)THEN
                                    DESCRIPTION := 'GMDR SCADA VOLUME เบี่ยงเบนเกิน GMDR SCADA ENERGY 5%';
                            INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(DATA3(COLHV).GASDAY,DATA3(COLHV).METER_ID,3,0,2,10,DESCRIPTION);
                        END IF;
                    END IF;
                ELSIF(DATA3(COLHV).GMDR_CLIENT_VOLUME != -2 AND DATA3(COLHV).GMDR_CLIENT_VOLUME IS NOT NULL
                   AND DATA3(COLHV).GMDR_CLIENT_ENERGY != -2 AND DATA3(COLHV).GMDR_CLIENT_ENERGY IS NOT NULL) THEN
                    VL_DEL_EN := DATA3(COLHV).GMDR_CLIENT_VOLUME * HV;
                    IF(VL_DEL_EN != 0)THEN
                        IF(ABS(DATA3(COLHV).GMDR_CLIENT_ENERGY - VL_DEL_EN / VL_DEL_EN * 100) > 5)THEN
                                    DESCRIPTION := 'GMDR CLIENT VOLUME เบี่ยงเบนเกิน GMDR CLIENT ENERGY 5%';
                            INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(DATA3(COLHV).GASDAY,DATA3(COLHV).METER_ID,4,0,2,10,DESCRIPTION);
                        END IF;
                    END IF;
                ELSIF(DATA3(COLHV).REALTIME_SCADA_VOLUME != -2 AND DATA3(COLHV).REALTIME_SCADA_VOLUME IS NOT NULL
                   AND DATA3(COLHV).REALTIME_SCADA_ENERGY != -2 AND DATA3(COLHV).REALTIME_SCADA_ENERGY IS NOT NULL) THEN
                    VL_DEL_EN := DATA3(COLHV).REALTIME_SCADA_VOLUME * HV;
                    IF(VL_DEL_EN != 0)THEN
                        IF(ABS(DATA3(COLHV).REALTIME_SCADA_ENERGY - VL_DEL_EN / VL_DEL_EN * 100) > 5)THEN
                                    DESCRIPTION := 'REALTIME SCADA VOLUME เบี่ยงเบนเกิน REALTIME SCADA ENERGY 5%';
                            INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(DATA3(COLHV).GASDAY,DATA3(COLHV).METER_ID,6,0,2,10,DESCRIPTION);
                        END IF;
                    END IF;
                ELSIF(DATA3(COLHV).ARCHIVE_SCADA_VOLUME != -2 AND DATA3(COLHV).ARCHIVE_SCADA_VOLUME IS NOT NULL
                    AND DATA3(COLHV).ARCHIVE_SCADA_ENERGY != -2 AND DATA3(COLHV).ARCHIVE_SCADA_ENERGY IS NOT NULL) THEN
                    VL_DEL_EN := DATA3(COLHV).ARCHIVE_SCADA_VOLUME * HV;
                    IF(VL_DEL_EN != 0)THEN
                        IF(ABS(DATA3(COLHV).ARCHIVE_SCADA_ENERGY - VL_DEL_EN / VL_DEL_EN * 100) > 5)THEN
                                    DESCRIPTION := 'ARCHIVE SCADA VOLUME เบี่ยงเบนเกิน ARCHIVE SCADA ENERGY 5%';
                            INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(DATA3(COLHV).GASDAY,DATA3(COLHV).METER_ID,5,0,2,10,DESCRIPTION);
                        END IF;
                    END IF;
                END IF;
            END LOOP;
        END LOOP;
    CLOSE VW_SUMMARY_DAILY_GET_DATA;
END RECORD_ALARM_QUANTITY_ABNORMAL_DEVIATE_PROCEDURE;