create or replace PROCEDURE                                                                                                                                                RECORD_ALARM_QUANTITY_ABNORMAL_HIGH_PROCEDURE (
    D IN DATE
) AS
    IS_COUNT_VOLUME                 INT := 0;
    IS_COUNT_ENERGY                 INT := 0;
    MAX_VOLUME                      INT := 1000000;
    MAX_ENERGY                      INT := 1000000000;
    IS_COUNT_MONTHLY_BILLING_VOLUME INT;
    IS_COUNT_DAILY_BILLING_VOLUME   INT;
    IS_COUNT_GMDR_SCADA_VOLUME      INT;
    IS_COUNT_GMDR_CLIENT_VOLUME     INT;
    IS_COUNT_REALTIME_SCADA_VOLUME  INT;
    IS_COUNT_ARCHIVE_SCADA_VOLUME   INT;
    IS_COUNT_MONTHLY_BILLING_ENERGY INT;
    IS_COUNT_DAILY_BILLING_ENERGY   INT;
    IS_COUNT_GMDR_SCADA_ENERGY      INT;
    IS_COUNT_GMDR_CLIENT_ENERGY     INT;
    IS_COUNT_REALTIME_SCADA_ENERGY  INT;
    IS_COUNT_ARCHIVE_SCADA_ENERGY   INT;
    DESCRIPTION                     VARCHAR(500 BYTE);
BEGIN
  FOR COL IN (SELECT * FROM TABLE ( MASTER_METER.SUMMARY_DAILY_GET_DATA_FUNCTION(TRUNC(D), TRUNC(D))))LOOP 
        IS_COUNT_VOLUME := 0;
        IS_COUNT_ENERGY := 0;
        IF ( COL.MONTHLY_BILLING_VOLUME < 0 ) THEN
            IS_COUNT_MONTHLY_BILLING_VOLUME := 0;
        ELSE
            IS_COUNT_MONTHLY_BILLING_VOLUME := 1;
        END IF;

        IF ( COL.DAILY_BILLING_VOLUME < 0 ) THEN
            IS_COUNT_DAILY_BILLING_VOLUME := 0;
        ELSE
            IS_COUNT_DAILY_BILLING_VOLUME := 1;
        END IF;

        IF ( COL.GMDR_SCADA_VOLUME < 0 ) THEN
            IS_COUNT_GMDR_SCADA_VOLUME := 0;
        ELSE
            IS_COUNT_GMDR_SCADA_VOLUME := 1;
        END IF;

        IF ( COL.GMDR_CLIENT_VOLUME < 0 ) THEN
            IS_COUNT_GMDR_CLIENT_VOLUME := 0;
        ELSE
            IS_COUNT_GMDR_CLIENT_VOLUME := 1;
        END IF;

        IF ( COL.REALTIME_SCADA_VOLUME < 0 ) THEN
            IS_COUNT_REALTIME_SCADA_VOLUME := 0;
        ELSE
            IS_COUNT_REALTIME_SCADA_VOLUME := 1;
        END IF;

        IF ( COL.ARCHIVE_SCADA_VOLUME < 0 ) THEN
            IS_COUNT_ARCHIVE_SCADA_VOLUME := 0;
        ELSE
            IS_COUNT_ARCHIVE_SCADA_VOLUME := 1;
        END IF;

        IF ( COL.MONTHLY_BILLING_ENERGY < 0 ) THEN
            IS_COUNT_MONTHLY_BILLING_ENERGY := 0;
        ELSE
            IS_COUNT_MONTHLY_BILLING_ENERGY := 1;
        END IF;

        IF ( COL.DAILY_BILLING_ENERGY < 0 ) THEN
            IS_COUNT_DAILY_BILLING_ENERGY := 0;
        ELSE
            IS_COUNT_DAILY_BILLING_ENERGY := 1;
        END IF;

        IF ( COL.GMDR_SCADA_ENERGY < 0 ) THEN
            IS_COUNT_GMDR_SCADA_ENERGY := 0;
        ELSE
            IS_COUNT_GMDR_SCADA_ENERGY := 1;
        END IF;

        IF ( COL.GMDR_CLIENT_ENERGY < 0 ) THEN
            IS_COUNT_GMDR_CLIENT_ENERGY := 0;
        ELSE
            IS_COUNT_GMDR_CLIENT_ENERGY := 1;
        END IF;

        IF ( COL.REALTIME_SCADA_ENERGY < 0 ) THEN
            IS_COUNT_REALTIME_SCADA_ENERGY := 0;
        ELSE
            IS_COUNT_REALTIME_SCADA_ENERGY := 1;
        END IF;

        IF ( COL.ARCHIVE_SCADA_ENERGY < 0 ) THEN
            IS_COUNT_ARCHIVE_SCADA_ENERGY := 0;
        ELSE
            IS_COUNT_ARCHIVE_SCADA_ENERGY := 1;
        END IF;
        
        IS_COUNT_VOLUME := IS_COUNT_MONTHLY_BILLING_VOLUME + IS_COUNT_DAILY_BILLING_VOLUME + IS_COUNT_GMDR_SCADA_VOLUME + IS_COUNT_GMDR_CLIENT_VOLUME +
        IS_COUNT_REALTIME_SCADA_VOLUME + IS_COUNT_ARCHIVE_SCADA_VOLUME;
        IS_COUNT_ENERGY := IS_COUNT_MONTHLY_BILLING_ENERGY + IS_COUNT_DAILY_BILLING_ENERGY + IS_COUNT_GMDR_SCADA_ENERGY + IS_COUNT_GMDR_CLIENT_ENERGY +
        IS_COUNT_REALTIME_SCADA_ENERGY + IS_COUNT_ARCHIVE_SCADA_ENERGY;
        
        IF ( IS_COUNT_VOLUME != 0 ) THEN
            IF(IS_COUNT_MONTHLY_BILLING_VOLUME = 1)THEN
                IF ( COL.MONTHLY_BILLING_VOLUME > MAX_VOLUME ) THEN
                     DESCRIPTION := 'MONTHLY BILLING VOLUME เกิน 1,000,000 ';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,1,0,2,7,DESCRIPTION);
                END IF;
            END IF;
            IF(IS_COUNT_DAILY_BILLING_VOLUME = 1 )THEN
                IF ( COL.DAILY_BILLING_VOLUME > MAX_VOLUME ) THEN
                     DESCRIPTION := 'DAILY BILLING VOLUME เกิน 1,000,000 ';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,2,0,2,7,DESCRIPTION);
                END IF;
            END IF;
            IF ( IS_COUNT_GMDR_SCADA_VOLUME = 1 ) THEN
                IF ( COL.GMDR_SCADA_VOLUME > MAX_VOLUME ) THEN
                     DESCRIPTION := 'GMDR SCADA VOLUME เกิน 1,000,000 ';
                        INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,3,0,2,7,DESCRIPTION);
                END IF;
            END IF;  
            IF ( IS_COUNT_GMDR_CLIENT_VOLUME = 1 ) THEN
                IF ( COL.GMDR_CLIENT_VOLUME > MAX_VOLUME ) THEN
                     DESCRIPTION := 'GMDR CLIENT VOLUME เกิน 1,000,000 ';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,4,0,2,7,DESCRIPTION);
                END IF;
            END IF;
            IF ( IS_COUNT_ARCHIVE_SCADA_VOLUME = 1 ) THEN
                IF ( COL.ARCHIVE_SCADA_VOLUME > MAX_VOLUME ) THEN
                     DESCRIPTION := 'ARCHIVE SCADA VOLUME เกิน 1,000,000 ';
            INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,5,0,2,7,DESCRIPTION);
                END IF;
            END IF;
            IF ( IS_COUNT_REALTIME_SCADA_VOLUME = 1 ) THEN
                IF ( COL.REALTIME_SCADA_VOLUME > MAX_VOLUME ) THEN
                     DESCRIPTION := 'REALTIME SCADA VOLUME เกิน 1,000,000 ';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,6,0,2,7,DESCRIPTION);
                END IF;
            END IF;
        END IF;
        IF ( IS_COUNT_ENERGY != 0 ) THEN
            IF ( IS_COUNT_MONTHLY_BILLING_ENERGY = 1 ) THEN
                IF ( COL.MONTHLY_BILLING_ENERGY > MAX_ENERGY ) THEN
                     DESCRIPTION := 'MONTHLY BILLING ENERGY เกิน 1,000,000,000 ';
            INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,1,0,2,7,DESCRIPTION);
                END IF;
            END IF;
            IF ( IS_COUNT_DAILY_BILLING_ENERGY = 1 ) THEN
                IF ( COL.DAILY_BILLING_ENERGY > MAX_ENERGY ) THEN
                     DESCRIPTION := 'DAILY BILLING ENERGY เกิน 1,000,000,000 ';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,2,0,2,7,DESCRIPTION);
                END IF;
            END IF;
            IF ( IS_COUNT_GMDR_SCADA_ENERGY = 1 ) THEN
                IF ( COL.GMDR_SCADA_ENERGY > MAX_ENERGY ) THEN
                     DESCRIPTION := 'GMDR SCADA ENERGY เกิน 1,000,000,000 ';
                     INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,3,0,2,7,DESCRIPTION);
                END IF;
            END IF;
            IF ( IS_COUNT_GMDR_CLIENT_ENERGY = 1 ) THEN
                IF ( COL.GMDR_CLIENT_ENERGY > MAX_ENERGY ) THEN
                     DESCRIPTION := 'GMDR CLIENT ENERGY เกิน 1,000,000,000 ';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,4,0,2,7,DESCRIPTION);
                END IF;
            END IF;
            IF ( IS_COUNT_ARCHIVE_SCADA_ENERGY = 1 ) THEN
                IF ( COL.ARCHIVE_SCADA_ENERGY > MAX_ENERGY ) THEN
                     DESCRIPTION := 'ARCHIVE SCADA ENERGY เกิน 1,000,000,000 ';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,5,0,2,7,DESCRIPTION);
                END IF;
            END IF;
            IF ( IS_COUNT_REALTIME_SCADA_ENERGY = 1 ) THEN
                IF ( COL.REALTIME_SCADA_ENERGY > MAX_ENERGY ) THEN
                     DESCRIPTION := 'REALTIME SCADA ENERGY เกิน 1,000,000,000 ';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,6,0,2,7,DESCRIPTION);
                END IF;
            END IF;
        END IF;
  END LOOP;
END RECORD_ALARM_QUANTITY_ABNORMAL_HIGH_PROCEDURE;