create or replace PROCEDURE                                                                                                                                   RECORD_ALARM_QUANTITY_ABNORMAL_COMPARE_PROCEDURE (
    D IN DATE
) AS
    IS_COUNT_MONTHLY_BILLING_VOLUME INT;
    IS_COUNT_DAILY_BILLING_VOLUME   INT;
    IS_COUNT_GMDR_SCADA_VOLUME      INT;
    IS_COUNT_GMDR_CLIENT_VOLUME     INT;
    IS_COUNT_REALTIME_SCADA_VOLUME  INT;
    IS_COUNT_ARCHIVE_SCADA_VOLUME   INT;
    IS_COUNT_MONTHLY_BILLING_ENERGY INT;
    IS_COUNT_DAILY_BILLING_ENERGY   INT;
    IS_COUNT_GMDR_SCADA_ENERGY      INT;
    IS_COUNT_GMDR_CLIENT_ENERGY     INT;
    IS_COUNT_REALTIME_SCADA_ENERGY  INT;
    IS_COUNT_ARCHIVE_SCADA_ENERGY   INT;
    VALUE_DAILY_VOLUME              FLOAT;
    VALUE_DAILY_ENERGY              FLOAT;
    THRESHOLD                       INT := 5;
    DESCRIPTION                     VARCHAR(500 BYTE);
BEGIN
    FOR COL IN (
        SELECT
            *
        FROM
            TABLE ( MASTER_METER.SUMMARY_DAILY_GET_DATA_FUNCTION(
                TRUNC(D), TRUNC(D)
            ) )
    ) LOOP
--Check Valid Source
        VALUE_DAILY_VOLUME := 0; 
        VALUE_DAILY_ENERGY := 0; 
        IF ( COL.MONTHLY_BILLING_VOLUME < 0 AND COL.MONTHLY_BILLING_VOLUME IS NOT NULL ) THEN
            IS_COUNT_MONTHLY_BILLING_VOLUME := 0;
        ELSE
            IS_COUNT_MONTHLY_BILLING_VOLUME := 1;
        END IF;

        IF ( COL.DAILY_BILLING_VOLUME < 0 AND COL.DAILY_BILLING_VOLUME IS NOT NULL ) THEN
            IS_COUNT_DAILY_BILLING_VOLUME := 0;
        ELSE
            IS_COUNT_DAILY_BILLING_VOLUME := 1;
            VALUE_DAILY_VOLUME := COL.DAILY_BILLING_VOLUME;
        END IF;
        IF ( COL.GMDR_SCADA_VOLUME < 0 AND COL.GMDR_SCADA_VOLUME IS NOT NULL ) THEN
            IS_COUNT_GMDR_SCADA_VOLUME := 0;
        ELSE
            IS_COUNT_GMDR_SCADA_VOLUME := 1;
        END IF;

        IF ( COL.GMDR_CLIENT_VOLUME < 0 AND COL.GMDR_CLIENT_VOLUME IS NOT NULL ) THEN
            IS_COUNT_GMDR_CLIENT_VOLUME := 0;
        ELSE
            IS_COUNT_GMDR_CLIENT_VOLUME := 1;
        END IF;

        IF ( COL.REALTIME_SCADA_VOLUME < 0 AND COL.REALTIME_SCADA_VOLUME IS NOT NULL ) THEN
            IS_COUNT_REALTIME_SCADA_VOLUME := 0;
        ELSE
            IS_COUNT_REALTIME_SCADA_VOLUME := 1;
        END IF;

        IF ( COL.ARCHIVE_SCADA_VOLUME < 0 AND COL.ARCHIVE_SCADA_VOLUME IS NOT NULL ) THEN
            IS_COUNT_ARCHIVE_SCADA_VOLUME := 0;
        ELSE
            IS_COUNT_ARCHIVE_SCADA_VOLUME := 1;
        END IF;

        IF ( COL.MONTHLY_BILLING_ENERGY < 0 AND COL.MONTHLY_BILLING_ENERGY IS NOT NULL ) THEN
            IS_COUNT_MONTHLY_BILLING_ENERGY := 0;
        ELSE
            IS_COUNT_MONTHLY_BILLING_ENERGY := 1;
        END IF;

        IF ( COL.DAILY_BILLING_ENERGY < 0 AND COL.DAILY_BILLING_ENERGY IS NOT NULL ) THEN
            IS_COUNT_DAILY_BILLING_ENERGY := 0;
        ELSE
            IS_COUNT_DAILY_BILLING_ENERGY := 1;
            VALUE_DAILY_ENERGY := COL.DAILY_BILLING_ENERGY;
        END IF;

        IF ( COL.GMDR_SCADA_ENERGY < 0 AND COL.GMDR_SCADA_ENERGY IS NOT NULL ) THEN
            IS_COUNT_GMDR_SCADA_ENERGY := 0;
        ELSE
            IS_COUNT_GMDR_SCADA_ENERGY := 1;
        END IF;

        IF ( COL.GMDR_CLIENT_ENERGY < 0 AND COL.GMDR_CLIENT_ENERGY IS NOT NULL ) THEN
            IS_COUNT_GMDR_CLIENT_ENERGY := 0;
        ELSE
            IS_COUNT_GMDR_CLIENT_ENERGY := 1;
        END IF;

        IF ( COL.REALTIME_SCADA_ENERGY < 0 AND COL.REALTIME_SCADA_ENERGY IS NOT NULL ) THEN
            IS_COUNT_REALTIME_SCADA_ENERGY := 0;
        ELSE
            IS_COUNT_REALTIME_SCADA_ENERGY := 1;
        END IF;

        IF ( COL.ARCHIVE_SCADA_ENERGY < 0 AND COL.ARCHIVE_SCADA_ENERGY IS NOT NULL ) THEN
            IS_COUNT_ARCHIVE_SCADA_ENERGY := 0;
        ELSE
            IS_COUNT_ARCHIVE_SCADA_ENERGY := 1;
        END IF;
        IF(IS_COUNT_DAILY_BILLING_VOLUME = 1 AND VALUE_DAILY_VOLUME != 0)THEN
            IF(IS_COUNT_MONTHLY_BILLING_VOLUME = 1) THEN
                IF(ABS((COL.MONTHLY_BILLING_VOLUME - VALUE_DAILY_VOLUME) / VALUE_DAILY_VOLUME) * 100 > THRESHOLD) THEN
                    DESCRIPTION := 'DAILY BILLING VOLUME เบี่ยงเบนจาก MONTHLY BILLING VOLUME เกิน 5%';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG (GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION
                    ) VALUES ( COL.GASDAY,COL.METER_ID,1,0,2,6,DESCRIPTION);
                    --DBMS_OUTPUT.PUT_LINE(ABS((COL.MONTHLY_BILLING_VOLUME - VALUE_DAILY_VOLUME) / VALUE_DAILY_VOLUME) * 100 || ' || ' || 'MONTHLY_BILLING_VOLUME ' || COL.METER_ID);
                END IF;
            END IF;
            IF(IS_COUNT_GMDR_SCADA_VOLUME = 1) THEN
                IF(ABS((COL.GMDR_SCADA_VOLUME - VALUE_DAILY_VOLUME) / VALUE_DAILY_VOLUME) * 100 > THRESHOLD) THEN
                    DESCRIPTION := 'DAILY BILLING VOLUME เบี่ยงเบนจาก GMDR SCADA VOLUME เกิน 5%';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG (GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION
                    ) VALUES ( COL.GASDAY,COL.METER_ID,3,0,2,6,DESCRIPTION);
                    --DBMS_OUTPUT.PUT_LINE(ABS((COL.GMDR_SCADA_VOLUME - VALUE_DAILY_VOLUME) / VALUE_DAILY_VOLUME) * 100 || ' || ' || 'GMDR_SCADA_VOLUME ' || COL.METER_ID);
                END IF;
            END IF;
            IF(IS_COUNT_GMDR_CLIENT_VOLUME = 1) THEN
                IF(ABS((COL.GMDR_CLIENT_VOLUME - VALUE_DAILY_VOLUME) / VALUE_DAILY_VOLUME) * 100 > THRESHOLD) THEN
                    DESCRIPTION := 'DAILY BILLING VOLUME เบี่ยงเบนจาก GMDR CLIENT VOLUME เกิน 5%';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG (GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION
                    ) VALUES ( COL.GASDAY,COL.METER_ID,4,0,2,6,DESCRIPTION);
                    --DBMS_OUTPUT.PUT_LINE(ABS((COL.GMDR_CLIENT_VOLUME - VALUE_DAILY_VOLUME ) / VALUE_DAILY_VOLUME) * 100 || ' || ' || 'GMDR_CLIENT_VOLUME ' || COL.METER_ID);
                END IF;
            END IF;
            IF(IS_COUNT_REALTIME_SCADA_VOLUME = 1) THEN
                IF(ABS((COL.REALTIME_SCADA_VOLUME - VALUE_DAILY_VOLUME) / VALUE_DAILY_VOLUME) * 100 > THRESHOLD) THEN
                    DESCRIPTION := 'DAILY BILLING VOLUME เบี่ยงเบนจาก REALTIME SCADA VOLUME เกิน 5%';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG (GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION
                    ) VALUES ( COL.GASDAY,COL.METER_ID,5,0,2,6,DESCRIPTION);
                    --DBMS_OUTPUT.PUT_LINE(ABS((COL.REALTIME_SCADA_VOLUME - VALUE_DAILY_VOLUME) / VALUE_DAILY_VOLUME) * 100 || ' || ' || 'REALTIME_SCADA_VOLUME ' || COL.METER_ID);
                END IF;
            END IF;
            IF(IS_COUNT_ARCHIVE_SCADA_VOLUME = 1) THEN
                IF(ABS((COL.ARCHIVE_SCADA_VOLUME - VALUE_DAILY_VOLUME) / VALUE_DAILY_VOLUME) * 100 > THRESHOLD) THEN
                    DESCRIPTION := 'DAILY BILLING VOLUME เบี่ยงเบนจาก ARCHIVE SCADA VOLUME เกิน 5%';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG (GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION
                    ) VALUES ( COL.GASDAY,COL.METER_ID,6,0,2,6,DESCRIPTION);
                    --DBMS_OUTPUT.PUT_LINE(ABS((COL.ARCHIVE_SCADA_VOLUME - VALUE_DAILY_VOLUME) / VALUE_DAILY_VOLUME) * 100 || ' || ' || 'ARCHIVE_SCADA_VOLUME ' || COL.METER_ID);
                END IF;
            END IF;
        END IF;
        IF(IS_COUNT_DAILY_BILLING_ENERGY = 1 AND VALUE_DAILY_ENERGY != 0)THEN
            IF(IS_COUNT_MONTHLY_BILLING_ENERGY = 1) THEN
                IF(ABS((COL.MONTHLY_BILLING_ENERGY - VALUE_DAILY_ENERGY) / VALUE_DAILY_ENERGY) * 100 > THRESHOLD) THEN
                    DESCRIPTION := 'DAILY BILLING ENERGY เบี่ยงเบนจาก MONTHLY BILLING ENERGY เกิน 5%';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG (GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION
                    ) VALUES ( COL.GASDAY,COL.METER_ID,1,0,2,6,DESCRIPTION);
                    --DBMS_OUTPUT.PUT_LINE(ABS((COL.MONTHLY_BILLING_ENERGY - VALUE_DAILY_ENERGY) / VALUE_DAILY_ENERGY) * 100 || ' || ' || 'MONTHLY_BILLING_ENERGY ' || COL.METER_ID);
                END IF;
            END IF;
            IF(IS_COUNT_GMDR_SCADA_ENERGY = 1) THEN
                IF(ABS((COL.GMDR_SCADA_ENERGY - VALUE_DAILY_ENERGY) / VALUE_DAILY_ENERGY) * 100 > THRESHOLD) THEN
                    DESCRIPTION := 'DAILY BILLING ENERGY เบี่ยงเบนจาก GMDR SCADA ENERGY เกิน 5%';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG (GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION
                    ) VALUES ( COL.GASDAY,COL.METER_ID,3,0,2,6,DESCRIPTION);
                    --DBMS_OUTPUT.PUT_LINE(ABS((COL.GMDR_SCADA_ENERGY - VALUE_DAILY_ENERGY) / VALUE_DAILY_ENERGY) * 100 || ' || ' || 'GMDR_SCADA_ENERGY ' || COL.METER_ID);
                END IF;
            END IF;
            IF(IS_COUNT_GMDR_CLIENT_ENERGY = 1) THEN
                IF(ABS((COL.GMDR_CLIENT_ENERGY - VALUE_DAILY_ENERGY) / VALUE_DAILY_ENERGY) * 100 > THRESHOLD) THEN
                    DESCRIPTION := 'DAILY BILLING ENERGY เบี่ยงเบนจาก GMDR CLIENT ENERGY เกิน 5%';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG (GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION
                    ) VALUES ( COL.GASDAY,COL.METER_ID,4,0,2,6,DESCRIPTION);
                    --DBMS_OUTPUT.PUT_LINE(ABS((COL.GMDR_CLIENT_ENERGY - VALUE_DAILY_ENERGY) / VALUE_DAILY_ENERGY) * 100 || ' || ' || 'GMDR_CLIENT_ENERGY ' || COL.METER_ID);
                END IF;
            END IF;
            IF(IS_COUNT_REALTIME_SCADA_ENERGY = 1) THEN
                IF(ABS((COL.REALTIME_SCADA_ENERGY - VALUE_DAILY_ENERGY) / VALUE_DAILY_ENERGY) * 100 > THRESHOLD) THEN
                    DESCRIPTION := 'DAILY BILLING ENERGY เบี่ยงเบนจาก REALTIME SCADA ENERGY เกิน 5%';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG (GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION
                    ) VALUES ( COL.GASDAY,COL.METER_ID,5,0,2,6,DESCRIPTION);
                    --DBMS_OUTPUT.PUT_LINE(ABS((COL.REALTIME_SCADA_ENERGY - VALUE_DAILY_ENERGY) / VALUE_DAILY_ENERGY) * 100 || ' || ' || 'REALTIME_SCADA_ENERGY ' || COL.METER_ID);
                END IF;
            END IF;
            IF(IS_COUNT_ARCHIVE_SCADA_ENERGY = 1) THEN
                IF(ABS((COL.ARCHIVE_SCADA_ENERGY - VALUE_DAILY_ENERGY) / VALUE_DAILY_ENERGY) * 100 > THRESHOLD) THEN
                    DESCRIPTION := 'DAILY BILLING ENERGY เบี่ยงเบนจาก ARCHIVE SCADA ENERGY เกิน 5%';
                    INSERT INTO MASTER_METER.ALARM_DATA_LOG (GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,ABNORMAL_CASE,DESCRIPTION
                    ) VALUES ( COL.GASDAY,COL.METER_ID,6,0,2,6,DESCRIPTION);
                    --DBMS_OUTPUT.PUT_LINE(ABS((COL.ARCHIVE_SCADA_ENERGY - VALUE_DAILY_ENERGY) / VALUE_DAILY_ENERGY) * 100 || ' || ' || 'ARCHIVE_SCADA_ENERGY ' || COL.METER_ID);
                END IF;
            END IF;
        END IF;
    END LOOP;
END RECORD_ALARM_QUANTITY_ABNORMAL_COMPARE_PROCEDURE;