create or replace PROCEDURE                                                                  RECORD_ALARM_QUANTITY_RAW_DATA_PROCEDURE
(
  GASDAY_INPUT IN DATE,
  MODEGET IN VARCHAR2 DEFAULT 'ALL' --'MONTHLY_BILLING_ENERGY, DAILY_BILLING_ENERGY, GMDR SCADA, GMDR CLIENT, ARCHIVE SCADA, REALTIME SCADA'
)
AS
DAY_NOW DATE := TO_DATE(TO_CHAR(sysdate, 'MM/DD/YYYY'), 'MM/DD/YYYY'); --Current Date
TIME24HR_NOW VARCHAR(50 byte) := TO_CHAR(SYSDATE, 'HH24:MI');
DESCRIPTION                     VARCHAR(500 BYTE);
--TO_CHAR(DAY_NOW , 'DD') = '10' AND 
BEGIN
    FOR COL IN (SELECT * FROM MASTER_METER.RECORD_DAILY_GET_QUANTITY_RAW_DATA WHERE TRUNC(GASDAY) = TRUNC(GASDAY_INPUT))
    LOOP
        IF(MODEGET = 'ALL' OR MODEGET = 'MONTHLY_BILLING_ENERGY') THEN
            IF(COL.MONTHLY_BILLING_ENERGY = -2) THEN 
                DESCRIPTION := 'MONTHLY BILLING ENERGY ค่าไม่เข้าวันที่ 10 ของเดือน';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,1,1,DESCRIPTION);
            END IF;
        END IF;
        IF(MODEGET = 'ALL' OR MODEGET = 'DAILY_BILLING_ENERGY') THEN
            IF(COL.DAILY_BILLING_ENERGY = -2) THEN 
                DESCRIPTION := 'DAILY BILLING ENERGY ค่าเข้าไม่ทันตอน 07:00 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,2,1,DESCRIPTION);
            END IF;
        END IF;
-------------------------------------------------------GMDR SCADA---------------------------------------------------------------------------
        IF(MODEGET = 'ALL' OR MODEGET = 'GMDR SCADA') THEN
            IF(COL.GMDR_SCADA_MAIN_1_SATSTDVOL = -2 AND COL.GMDR_SCADA_MAIN_1_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR SCADA MAIN 1 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,3,1,1,DESCRIPTION);   
            END IF;
            IF(COL.GMDR_SCADA_MAIN_2_SATSTDVOL = -2 AND COL.GMDR_SCADA_MAIN_2_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR SCADA MAIN 2 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,3,2,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_SCADA_MAIN_3_SATSTDVOL = -2 AND COL.GMDR_SCADA_MAIN_3_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR SCADA MAIN 3 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,3,3,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_SCADA_MAIN_4_SATSTDVOL = -2 AND COL.GMDR_SCADA_MAIN_4_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR SCADA MAIN 4 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,3,4,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_SCADA_MAIN_5_SATSTDVOL = -2 AND COL.GMDR_SCADA_MAIN_5_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR SCADA MAIN 5 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,3,5,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_SCADA_MAIN_6_SATSTDVOL = -2 AND COL.GMDR_SCADA_MAIN_6_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR SCADA MAIN 6 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,3,6,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_SCADA_BACK_1_SATSTDVOL = -2 AND COL.GMDR_SCADA_BACK_1_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR SCADA BACK 1 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,3,7,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_SCADA_BACK_2_SATSTDVOL = -2 AND COL.GMDR_SCADA_BACK_2_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR SCADA BACK 2 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,3,8,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_SCADA_BACK_3_SATSTDVOL = -2 AND COL.GMDR_SCADA_BACK_3_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR SCADA BACK 3 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,3,9,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_SCADA_BACK_4_SATSTDVOL = -2 AND COL.GMDR_SCADA_BACK_4_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR SCADA BACK 4 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,3,10,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_SCADA_BACK_5_SATSTDVOL = -2 AND COL.GMDR_SCADA_BACK_5_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR SCADA BACK 5 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,3,11,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_SCADA_BACK_6_SATSTDVOL = -2 AND COL.GMDR_SCADA_BACK_6_STDVOL = -2) THEN 
                DESCRIPTION := 'GMDR SCADA BACK 6 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,3,12,1,DESCRIPTION);
            END IF;
        END IF;
-------------------------------------------------------GMDR CLIENT---------------------------------------------------------------------------
        IF(MODEGET = 'ALL' OR MODEGET = 'GMDR CLIENT') THEN
            IF(COL.GMDR_CLIENT_MAIN_1_SATSTDVOL = -2 AND COL.GMDR_CLIENT_MAIN_1_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR CLIENT MAIN 1 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,4,1,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_CLIENT_MAIN_2_SATSTDVOL = -2 AND COL.GMDR_CLIENT_MAIN_2_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR CLIENT MAIN 2 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,4,2,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_CLIENT_MAIN_3_SATSTDVOL = -2 AND COL.GMDR_CLIENT_MAIN_3_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR CLIENT MAIN 3 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,4,3,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_CLIENT_MAIN_4_SATSTDVOL = -2 AND COL.GMDR_CLIENT_MAIN_4_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR CLIENT MAIN 4 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,4,4,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_CLIENT_MAIN_5_SATSTDVOL = -2 AND COL.GMDR_CLIENT_MAIN_5_STDVOL = -2) THEN
                 DESCRIPTION := 'GMDR CLIENT MAIN 5 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                 INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,4,5,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_CLIENT_MAIN_6_SATSTDVOL = -2 AND COL.GMDR_CLIENT_MAIN_6_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR CLIENT MAIN 6 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,4,6,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_CLIENT_BACK_1_SATSTDVOL = -2 AND COL.GMDR_CLIENT_BACK_1_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR CLIENT BACK 1 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,4,7,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_CLIENT_BACK_2_SATSTDVOL = -2 AND COL.GMDR_CLIENT_BACK_2_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR CLIENT BACK 2 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,4,8,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_CLIENT_BACK_3_SATSTDVOL = -2 AND COL.GMDR_CLIENT_BACK_3_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR CLIENT BACK 3 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,4,9,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_CLIENT_BACK_4_SATSTDVOL = -2 AND COL.GMDR_CLIENT_BACK_4_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR CLIENT BACK 4 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,4,10,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_CLIENT_BACK_5_SATSTDVOL = -2 AND COL.GMDR_CLIENT_BACK_5_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR CLIENT BACK 5 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,4,11,1,DESCRIPTION);
            END IF;
            IF(COL.GMDR_CLIENT_BACK_6_SATSTDVOL = -2 AND COL.GMDR_CLIENT_BACK_6_STDVOL = -2) THEN
                DESCRIPTION := 'GMDR CLIENT BACK 6 SATSTDVOL ค่าเข้าไม่ทันตอน 01:30 AM';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,4,12,1,DESCRIPTION);
            END IF;
        END IF;
-------------------------------------------------------ARCHIVE SCADA---------------------------------------------------------------------------
        IF(MODEGET = 'ALL' OR MODEGET = 'ARCHIVE SCADA') THEN
            IF(COL.ARCHIVE_SCADA_VOLUME_TAG_1 = -2 AND COL.ARCHIVE_SCADA_ENERGY_TAG_1 = -2) THEN
                DESCRIPTION := 'ARCHIVE SCADA VOLUME TAG 1 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,5,1,1,DESCRIPTION);
            END IF;
            IF(COL.ARCHIVE_SCADA_VOLUME_TAG_2 = -2 AND COL.ARCHIVE_SCADA_ENERGY_TAG_2 = -2) THEN
                DESCRIPTION := 'ARCHIVE SCADA VOLUME TAG 2 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,5,2,1,DESCRIPTION);
            END IF;
            IF(COL.ARCHIVE_SCADA_VOLUME_TAG_3 = -2 AND COL.ARCHIVE_SCADA_ENERGY_TAG_3 = -2) THEN
                DESCRIPTION := 'ARCHIVE SCADA VOLUME TAG 3 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,5,3,1,DESCRIPTION);
            END IF;
            IF(COL.ARCHIVE_SCADA_VOLUME_TAG_4 = -2 AND COL.ARCHIVE_SCADA_ENERGY_TAG_4 = -2) THEN
                DESCRIPTION := 'ARCHIVE SCADA VOLUME TAG 4 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,5,4,1,DESCRIPTION); 
            END IF;
            IF(COL.ARCHIVE_SCADA_VOLUME_TAG_5 = -2 AND COL.ARCHIVE_SCADA_ENERGY_TAG_5 = -2) THEN
                DESCRIPTION := 'ARCHIVE SCADA VOLUME TAG 5 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,5,5,1,DESCRIPTION);
            END IF;
            IF(COL.ARCHIVE_SCADA_VOLUME_TAG_6 = -2 AND COL.ARCHIVE_SCADA_ENERGY_TAG_6 = -2) THEN
                DESCRIPTION := 'ARCHIVE SCADA VOLUME TAG 6 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,5,6,1,DESCRIPTION); 
            END IF;
            IF(COL.ARCHIVE_SCADA_ENERGY_TAG_1 = -2 AND COL.ARCHIVE_SCADA_ENERGY_TAG_1 = -2) THEN
                DESCRIPTION := 'ARCHIVE SCADA ENERGY TAG 1 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,5,7,1,DESCRIPTION); 
            END IF;
            IF(COL.ARCHIVE_SCADA_ENERGY_TAG_2 = -2 AND COL.ARCHIVE_SCADA_ENERGY_TAG_2 = -2) THEN
                DESCRIPTION := 'ARCHIVE SCADA ENERGY TAG 2 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,5,8,1,DESCRIPTION); 
            END IF;
            IF(COL.ARCHIVE_SCADA_ENERGY_TAG_3 = -2 AND COL.ARCHIVE_SCADA_ENERGY_TAG_3 = -2) THEN
                DESCRIPTION := 'ARCHIVE SCADA ENERGY TAG 3 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,5,9,1,DESCRIPTION); 
            END IF;
            IF(COL.ARCHIVE_SCADA_ENERGY_TAG_4 = -2 AND COL.ARCHIVE_SCADA_ENERGY_TAG_4 = -2) THEN
                DESCRIPTION := 'ARCHIVE SCADA ENERGY TAG 4 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,5,10,1,DESCRIPTION); 
            END IF;
            IF(COL.ARCHIVE_SCADA_ENERGY_TAG_5 = -2 AND COL.ARCHIVE_SCADA_ENERGY_TAG_5 = -2) THEN
                DESCRIPTION := 'ARCHIVE SCADA ENERGY TAG 5 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,5,11,1,DESCRIPTION); 
            END IF;
            IF(COL.ARCHIVE_SCADA_ENERGY_TAG_6 = -2 AND COL.ARCHIVE_SCADA_ENERGY_TAG_6 = -2) THEN
                DESCRIPTION := 'ARCHIVE SCADA ENERGY TAG 6 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,5,12,1,DESCRIPTION); 
            END IF;
        END IF;
-------------------------------------------------------REALTIME SCADA---------------------------------------------------------------------------
        IF(MODEGET = 'ALL' OR MODEGET = 'REALTIME SCADA') THEN
            IF(COL.REALTIME_SCADA_VOLUME_TAG_1 = -2 AND COL.REALTIME_SCADA_VOLUME_TAG_1 = -2) THEN
                DESCRIPTION := 'REALTIME SCADA VOLUME TAG 1 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,6,1,1,DESCRIPTION);
            END IF;
            IF(COL.REALTIME_SCADA_VOLUME_TAG_2 = -2 AND COL.REALTIME_SCADA_VOLUME_TAG_2 = -2) THEN
                DESCRIPTION := 'REALTIME SCADA VOLUME TAG 2 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,6,2,1,DESCRIPTION);
            END IF;
            IF(COL.REALTIME_SCADA_VOLUME_TAG_3 = -2 AND COL.REALTIME_SCADA_VOLUME_TAG_3 = -2) THEN
                DESCRIPTION := 'REALTIME SCADA VOLUME TAG 3 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,6,3,1,DESCRIPTION);
            END IF;
            IF(COL.REALTIME_SCADA_VOLUME_TAG_4 = -2 AND COL.REALTIME_SCADA_VOLUME_TAG_4 = -2) THEN
                DESCRIPTION := 'REALTIME SCADA VOLUME TAG 4 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,6,4,1,DESCRIPTION);
            END IF;
            IF(COL.REALTIME_SCADA_VOLUME_TAG_5 = -2 AND COL.REALTIME_SCADA_VOLUME_TAG_5 = -2) THEN
                DESCRIPTION := 'REALTIME SCADA VOLUME TAG 5 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,6,5,1,DESCRIPTION);
            END IF;
            IF(COL.REALTIME_SCADA_VOLUME_TAG_6 = -2 AND COL.REALTIME_SCADA_VOLUME_TAG_6 = -2) THEN
                DESCRIPTION := 'REALTIME SCADA VOLUME TAG 6 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,6,6,1,DESCRIPTION);
            END IF;
            IF(COL.REALTIME_SCADA_ENERGY_TAG_1 = -2 AND COL.REALTIME_SCADA_ENERGY_TAG_1 = -2) THEN
                DESCRIPTION := 'REALTIME SCADA ENERGY TAG 1 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,6,7,1,DESCRIPTION);
            END IF;
            IF(COL.REALTIME_SCADA_ENERGY_TAG_2 = -2 AND COL.REALTIME_SCADA_ENERGY_TAG_2 = -2) THEN
                DESCRIPTION := 'REALTIME SCADA ENERGY TAG 2 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,6,8,1,DESCRIPTION);
            END IF;
            IF(COL.REALTIME_SCADA_ENERGY_TAG_3 = -2 AND COL.REALTIME_SCADA_ENERGY_TAG_3 = -2) THEN
                DESCRIPTION := 'REALTIME SCADA ENERGY TAG 3 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,6,9,1,DESCRIPTION);
            END IF;
            IF(COL.REALTIME_SCADA_ENERGY_TAG_4 = -2 AND COL.REALTIME_SCADA_ENERGY_TAG_4 = -2) THEN
                DESCRIPTION := 'REALTIME SCADA ENERGY TAG 4 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,6,10,1,DESCRIPTION);
            END IF;
            IF(COL.REALTIME_SCADA_ENERGY_TAG_5 = -2 AND COL.REALTIME_SCADA_ENERGY_TAG_5 = -2) THEN
                DESCRIPTION := 'REALTIME SCADA ENERGY TAG 5 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,6,11,1,DESCRIPTION);
            END IF;
            IF(COL.REALTIME_SCADA_ENERGY_TAG_6 = -2 AND COL.REALTIME_SCADA_ENERGY_TAG_6 = -2) THEN
                DESCRIPTION := 'REALTIME SCADA ENERGY TAG 6 ค่าไม่เข้า';
                INSERT INTO MASTER_METER.ALARM_DATA_LOG(GASDAY,METER_ID,SOURCE,RUN,ERROR_TYPE,DESCRIPTION)VALUES(COL.GASDAY,COL.METER_ID,6,12,1,DESCRIPTION);
            END IF;
        END IF;
    END LOOP;
END RECORD_ALARM_QUANTITY_RAW_DATA_PROCEDURE;